### ISSUE TITLE
Check if a variable exists

### ISSUE THREAD

**Issue by iganinja** [ThePhD/sol2#43]
Hi

I have updated my code to use sol2 (it was easy, just change very few method names was enough) and everything is working fine, but I have a small question: how can I know if a variable is set or not in the script? I want to do something like this:

config.lua
    
    fullScreen = true

In C++:

    sol::state vm;
    vm.script_file("config.lua");

    bool isFullScreen = true; // Default value

    if(vm.exists("fullScreen"))
    {
        isFullScreen = vm["fullScreen"]; // Get user configuration
    }

Is it possible to do something equivalent to this in sol2? How?

Thank you very much

**Comment by Nava2** [comment]
In C++:

```
auto fullscreen = vm["fullscreen"];
if (fullscreen.valid()) 
{
  isFullScreen = fullscreen;
}
```

**Comment by iganinja** [comment]
Thanks for the answer Nava2. Unfortunately it seems it's not working in sol2-2.1.0:

    error: 'struct sol::proxy<sol::table_core<true>&, const char (&)[11]>' has no member named 'valid'
     if(fullScreen.valid())
                   ^

**Comment by ThePhD** [comment]
I should add a `.valid()` method to `proxy`, since for all intents and purpose it might as well be there, to make @Nava2's code work. But the other way is:

````
auto fullscreen = vm["fullscreen"];
if (fullscreen != sol::nil) {
    isFullScreen = fullscreen;
}
````

I should explicitly document this somewhere too.

**Comment by ThePhD** [comment]
Updated the latest release: the code @Nava2 wrote will work.
