### ISSUE TITLE
Minimal example using cmake and system provided lua 5.4.3 on Fedora fails to compile

### ISSUE THREAD

**Issue by robertu94** [ThePhD/sol2#1258]
First of all, thank you for all of your great work on sol2 and the C and C++ standards committees!

I attached a Dockerfile and small example code that will replicate a minimal version of my build environment.  [sol2bug.zip](https://github.com/ThePhD/sol2/files/7349815/sol2bug.zip)  If this doesn't work for you or provide all the detail you need please let me know.

To use it do the following:

```bash
#unpack and build the container
unzip sol2bug.zip
cd sol2bug
docker build . -t sol2bug
docker run -it --rm sol2bug
#now you are in the container
cmake -S . -B build
cmake --build
# compiler error
```
which in turn generates the following compiler error:

```console
[ 50%] Building CXX object CMakeFiles/sol2_bug.dir/example.cc.o
In file included from /user/include/sol/sol.hpp:25,
                 from /example/example.cc:1:
/user/include/sol/detail/build_version.hpp:49:7: error: missing binary operator before token "3"
   49 | #elif SOL_IS_ON() && (defined(DLL_) || defined(_DLL))
      |       ^~~~~~~~~
In file included from /user/include/sol/compatibility.hpp:33,
                 from /user/include/sol/bytecode.hpp:27,
                 from /user/include/sol/sol.hpp:51,
                 from /example/example.cc:1:
/user/include/sol/compatibility/lua_version.hpp:195:177: error: operator '!=' has no left operand
  195 | TLIB != 0)) || (SOL_LUA_VERSION_I_ < 504 && (defined(LUA_COMPAT_5_2) && (LUA_COMPAT_5_2 != 0)))
      |                                                                                         ^~

In file included from /user/include/sol/sol.hpp:25,
                 from /example/example.cc:1:
/user/include/sol/demangle.hpp:50:75: error: missing binary operator before token "SOL_COMPILER_VCXX_CLANG_I_"
   50 | #if SOL_IS_ON(SOL_COMPILER_GCC_I_) || SOL_IS_ON(SOL_COMPILER_CLANG_I_) || SOL_IS_ON(SOL_COMPILER_VCXX_CLANG_I_)
      |                                                                           ^~~~~~~~~
In file included from /user/include/sol/usertype_traits.hpp:27,
                 from /user/include/sol/inheritance.hpp:28,
                 from /user/include/sol/stack_core.hpp:28,
                 from /user/include/sol/stack.hpp:28,
                 from /user/include/sol/sol.hpp:52,
                 from /example/example.cc:1:
/user/include/sol/demangle.hpp:126:2: error: #error Compiler not supported for demangling
  126 | #error Compiler not supported for demangling
      |  ^~~~~
In file included from /user/include/sol/table_core.hpp:31,
                 from /user/include/sol/metatable.hpp:27,
                 from /user/include/sol/usertype.hpp:31,
                 from /user/include/sol/sol.hpp:56,
                 from /example/example.cc:1:
/user/include/sol/pairs_iterator.hpp:34:10: fatal error: sol/detail/pairs.hpp: No such file or directory
   34 | #include <sol/detail/pairs.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
gmake[2]: *** [CMakeFiles/sol2_bug.dir/build.make:76: CMakeFiles/sol2_bug.dir/example.cc.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/sol2_bug.dir/all] Error 2
gmake: *** [Makefile:91: all] Error 2

```

I normally try to provide PRs to just fix issues like this, but I am having a hard time tracing all the macros.

Included in the zip file is a patch that was required to even get it to compile on Fedora 34.

**Comment by robertu94** [comment]
@ThePhD could this issue be re-opened?  I know you are busy, but this still doesn't work.

**Comment by dns13** [comment]
It does not work for me, too with Lua 5.4.4 on Fedora 38. It seems, that `LUA_COMPAT_5_2` is defined, but has no value, so the check `LUA_COMPAT_5_2 != 0` is invalid code. It's working with my custom compiled 5.4.4.
