### ISSUE TITLE
gcc-8 compilation error c_call to type lua_CFunction.

### ISSUE THREAD

**Issue by reworks** [ThePhD/sol2#735]
Compiler: gcc 8.2.0
OS: Ubuntu 18.04.1 x64
Sol2 version: v2.20.6 (revision c61a434). Single Header.
Lua version: 5.3.5
Flags: -m64 -Og -g -std=c++17 -lstdc++fs
Compiling as: Debug, x64.

Specific error messages:
```
sol.hpp:18239:13: error: no matches converting function ‘c_call’ to type ‘lua_CFunction’ {aka ‘int (*)(struct lua_State*)’}
    l[index] = luaL_Reg{ name, &c_call<decltype(static_cast<sz_func>(&T::size)), static_cast<sz_func>(&T::size)> };

sol.hpp:13878:13: note: candidates are: ‘template<class ... Fxs> int sol::c_call(lua_State*)’
  inline int c_call(lua_State* L) {
             ^~~~~~
source/sl/libs/sol2/sol.hpp:13858:13: note:                 ‘template<class F, F fx> int sol::c_call(lua_State*)’
  inline int c_call(lua_State* L) {
```

and

```
sol.hpp:18239:13: error: no matches converting function ‘c_call’ to type ‘lua_CFunction’ {aka ‘int (*)(struct lua_State*)’}
    l[index] = luaL_Reg{ name, &c_call<decltype(static_cast<sz_func>(&T::size)), static_cast<sz_func>(&T::size)> };


sol.hpp:13878:13: note: candidates are: ‘template<class ... Fxs> int sol::c_call(lua_State*)’
  inline int c_call(lua_State* L) {
             ^~~~~~
source/sl/libs/sol2/sol.hpp:13858:13: note:                 ‘template<class F, F fx> int sol::c_call(lua_State*)’
  inline int c_call(lua_State* L) {
             ^~~~~~
```

I saw that 2.20.1 did not support gcc 8 but the docs did say newer versions would, unless I am mistaken? But I am definitely using 2.20.6.
This did compile on Visual Studio 17 15.9.2 w/ C++17 (latest compiler). Although I do know that gcc is stricter than VS so it might be my code.
Sorry if this issue is incorrect, if it is I will close asap.

Can supply other code if need be.
Entire error message: https://pastebin.com/5HPiTk28

**Comment by ThePhD** [comment]
It means sol2 won't mind to_string to __tostring, operator< to __lt, and etc. for the usertype. That's all.

Whether you care about those special functions types and their semantics being bound from sol2 is a different matter.

**Comment by reworks** [comment]
Kinda weird because:
```cpp
// No Issues
m_world->m_lua.new_usertype<Rect<int>>("iRect",
			sol::constructors<Rect<int>(), Rect<int>(int, int, int, int)>(),
			"contains", sol::overload(sol::resolve<bool(int, int)>(&Rect<int>::contains), sol::resolve<bool(const Rect<int>&)>(&Rect<int>::contains)),
			"x", &Rect<int>::m_x,
			"y", &Rect<int>::m_y,
			"width", &Rect<int>::m_width,
			"height", &Rect<int>::m_height
		);

               // No issues
		m_world->m_lua.new_usertype<Rect<float>>("fRect",
			sol::constructors<Rect<float>(), Rect<float>(float, float, float, float)>(),
			"contains", sol::overload(sol::resolve<bool(float, float)>(&Rect<float>::contains), sol::resolve<bool(const Rect<float>&)>(&Rect<float>::contains)),
			"x", &Rect<float>::m_x,
			"y", &Rect<float>::m_y,
			"width", &Rect<float>::m_width,
			"height", &Rect<float>::m_height
		);

                // Needs automagical disabled
		m_world->m_lua.new_usertype<Rect<float, int>>("fiRect",
			sol::constructors<Rect<float, int>(), Rect<float, int>(float, float, int, int)>(),
			"contains", sol::overload(sol::resolve<bool(float, float)>(&Rect<float, int>::contains), sol::resolve<bool(const Rect<float, int>&)>(&Rect<float, int>::contains)),
			"x", &Rect<float, int>::m_x,
			"y", &Rect<float, int>::m_y,
			"width", &Rect<float, int>::m_width,
			"height", &Rect<float, int>::m_height
);
```

Dunno if this is a problem with my class or not but your solution worked. Should I go ahead and close the issue?

Thank you! :)

**Comment by ThePhD** [comment]
I don't know what `Rect` looks like / is, I can't comment.

**Comment by reworks** [comment]
Rect.hpp:
```cpp
#ifndef STARLIGHT_RECT_HPP_
#define STARLIGHT_RECT_HPP_

#include "sl/libs/cereal/access.hpp"

namespace sl
{
	///
	/// Represents a rectangle object.
	///
	template<typename T1, typename T2 = T1>
	class Rect final
	{
		friend class cereal::access;
	public:
		///
		/// Default constructor. Values are initialized to 0.
		///
		Rect();

		///
		/// Value constructor.
		///
		/// \param x X value.
		/// \param y Y value.
		/// \param width Width value.
		/// \param height Height value.
		///
		Rect(T1 x, T1 y, T2 width, T2 height);

		///
		/// Does the rectangle contain the point (x, y).
		///
		/// \param x X coordinate.
		/// \param y Y coordinate.
		///
		/// \return true if contains the point.
		///
		bool contains(T1 x, T1 y);

		///
		/// Does the rectangle contain another rectangle.
		///
		/// \param b Rectangle to check.
		///
		/// \return Returns true if the rectangle is completely inside, not on the edge.
		///
		bool contains(const Rect<T1, T2>& b);

		///
		/// Do the rectangles a and b overlap.
		///
		/// \param b Right rectangle.
		///
		/// \return Returns true if there is an overlap.
		///
		bool overlaps(const Rect<T1, T2>& b);

	private:
		///
		/// Private function to determine if value is in range.
		/// From: https://stackoverflow.com/a/306379
		///
		bool valueInRange(T1 value, T1 min, T1 max);

		///
		/// Cereal serialize function.
		///
		template <class Archive>
		void serialize(Archive& ar)
		{
			ar(m_x, m_y, m_width, m_height);
		}

	public:
		///
		/// x position.
		///
		T1 m_x;

		///
		/// y position.
		///
		T1 m_y;

		///
		/// width of rectangle.
		///
		T2 m_width;

		///
		/// height of rectangle.
		///
		T2 m_height;
	};

	template<typename T1, typename T2>
	Rect<T1, T2>::Rect()
		:m_x(0), m_y(0), m_width(0), m_height(0)
	{
		// Default constructor.
	}

	template<typename T1, typename T2>
	Rect<T1, T2>::Rect(T1 x, T1 y, T2 width, T2 height)
		: m_x(x), m_y(y), m_width(width), m_height(height)
	{
		// Argument constructor.
	}

	template<typename T1, typename T2>
	bool Rect<T1, T2>::contains(T1 x, T1 y)
	{
		// Checks if the rectangle contains the point (x, y) using some basic math.
		bool out = ((x > m_x) && (x < (m_x + m_width)) && (y > m_y) && (y < (m_y + m_height))) ? true : false;

		return out;
	}

	template<typename T1, typename T2>
	bool Rect<T1, T2>::contains(const Rect<T1, T2>& b)
	{
		// Checks if the rectangle contains another rectangle using math.
		bool out = ((b.m_x + b.m_width) < (m_x + m_width) && (b.m_x) > (m_x) && (b.m_y) >(m_y) && (b.m_y + b.m_height) < (m_y + m_height)) ? true : false;

		return out;
	}

	template<typename T1, typename T2>
	bool Rect<T1, T2>::overlaps(const Rect<T1, T2>& b)
	{
		// Thanks: https://stackoverflow.com/a/306379

		// Check for overlaps using math.
		bool xOverlap = valueInRange(m_x, b.m_x, b.m_x + b.m_width) ||
			valueInRange(b.m_x, m_x, m_x + m_width);

		bool yOverlap = valueInRange(m_y, b.m_y, b.m_y + b.m_height) ||
			valueInRange(b.m_y, m_y, m_y + m_height);

		return xOverlap && yOverlap;
	}

	template<typename T1, typename T2>
	bool Rect<T1, T2>::valueInRange(T1 value, T1 min, T1 max)
	{
		// Check if a value is between min and max - i.e. in range.
		return (value >= min) && (value <= max);
	}

	template<typename T1, typename T2>
	Rect<T1, T2> operator-(const Rect<T1, T2>& a)
	{
		// Negative operator overloading.
		return Rect<T1, T2>(-a.m_x, -a.m_y, -a.m_width, -a.m_height);
	}

	template<typename T1, typename T2>
	Rect<T1, T2>& operator+=(Rect<T1, T2>& a, const Rect<T1, T2>& b)
	{
		// Addition assignment operator overloading.
		a.m_x += b.m_x;
		a.m_y += b.m_y;
		a.m_width += b.m_width;
		a.m_height += a.m_height;

		return a;
	}

	template<typename T1, typename T2>
	Rect<T1, T2>& operator-=(Rect<T1, T2>& a, const Rect<T1, T2>& b)
	{
		// Subtraction assignment operator overloading.
		a.m_x -= b.m_x;
		a.m_y -= b.m_y;
		a.m_width -= b.m_width;
		a.m_height -= b.m_height;

		return a;
	}

	template<typename T1, typename T2>
	Rect<T1, T2> operator+(const Rect<T1, T2>& a, const Rect<T1, T2>& b)
	{
		return Rect<T1, T2>(a.m_x + b.m_x, a.m_y + b.m_y, a.m_z + b.m_z);
	}

	template<typename T1, typename T2>
	Rect<T1, T2> operator-(const Rect<T1, T2>& a, const Rect<T1, T2>& b)
	{
		// Subtraction operator overloading.
		return Rect<T1, T2>(a.m_x - b.m_x, a.m_y - b.m_y, a.m_width - b.m_width, a.m_height - b.m_height);
	}

	template<typename T1, typename T2>
	bool operator==(const Rect<T1, T2>& a, const Rect<T1, T2>& b)
	{
		// Equality operator overloading.
		return (a.m_x == b.m_x) && (a.m_y == b.m_y) && (a.m_width == b.m_width) && (a.m_height == b.m_height);
	}

	template<typename T1, typename T2>
	bool operator!=(const Rect<T1, T2>& a, const Rect<T1, T2>& b)
	{
		// Not equal to operator overloading.
		return (a.m_x != b.m_x) || (a.m_y != b.m_y) || (a.m_width != b.m_width) || (a.m_height != b.m_height);
	}
}

#endif
```

I'll go ahead and close this since it was solved.
