### ISSUE TITLE
Compilation error: symbols already defined? LuaJIT, sol2 and Unreal Engine

### ISSUE THREAD

**Issue by Sixmorphugus** [ThePhD/sol2#428]
Hi,
I'm getting something similar to #208.

![](https://cdn.discordapp.com/attachments/322427083017945091/325635200807600130/unknown.png)
I'm using 
- LuaJIT 2.1 beta 3 (have also tried stable)
- Sol 2.17

I've tried building it with Visual Studio 2015 and 2017 (Unreal Build Tool)

Defining `SOL_NO_COMPAT 1` gives me an avalanche of errors. I've also tried including luajit above sol, using the single version of sol, etc.

**Comment by ThePhD** [comment]
This should be gated behind a `SOL_LUAJIT_VERSION` macro. When I build with LuaJIT 2.1 beta3, beta2, and LuaJIT 2.0, I do not get an LNK error even when I have to build across multiple cpp files, so I'm having a hard time reproducing your code.

**Comment by Sixmorphugus** [comment]
I made some progress on this: It seems like I was including the wrong files for the static version of LuaJIT, but fixing that (so I have LuaJIT 2.1 beta 3 headers and libraries rather than two accidentally different versions) just uncovers new errors:
```
1>lua51.lib(lj_api.obj) : error LNK2005: luaL_setmetatable already defined in LuaState.cpp.obj
1>lua51.lib(lj_api.obj) : error LNK2005: luaL_testudata already defined in LuaState.cpp.obj
1>lua51.lib(lj_api.obj) : error LNK2005: lua_copy already defined in LuaState.cpp.obj
1>lua51.lib(lj_api.obj) : error LNK2005: lua_tointegerx already defined in LuaState.cpp.obj
1>lua51.lib(lj_api.obj) : error LNK2005: lua_tonumberx already defined in LuaState.cpp.obj
1>lua51.lib(lj_api.obj) : error LNK2005: lua_version already defined in LuaState.cpp.obj
1>lua51.lib(lib_aux.obj) : error LNK2005: luaL_setfuncs already defined in LuaState.cpp.obj
```

**Comment by Sixmorphugus** [comment]
I've found where luaJIT defines these symbols, if it's any help:
https://github.com/LuaJIT/LuaJIT/blob/v2.1/src/lua.h

**Comment by ThePhD** [comment]
I pulled a fresh LuaJIT 2.1.0-beta3 from luajit's website. I put it in alongside sol2. I built the library with `msvcbuild.bat`. I compiled and ran not only the test suite but a small sample program as well. I received none of the redefinition errors.

Unless you're doing something special, I don't have answers for you. Maybe something's changed for `v2.1` on github's latest/greatest branch, but I really can't be tracking neck-breaking latest additions done by LuaJIT's beta3 branch on github or similar.

Have you tried running your program with the officially given LuaJIT-beta3 available from the website?

**Comment by Sixmorphugus** [comment]
Hi,
Yes, that's the version we're using. Are you linking luaJIT statically?

**Comment by Sixmorphugus** [comment]
Like for example, there are symbols here:
https://github.com/LuaJIT/LuaJIT/blob/v2.1/src/lua.h#L347
That are defined here:
https://github.com/ThePhD/sol2/blob/develop/sol/compatibility/5.x.x.h#L48

I don't know if the compatibility header needs an update because luajit ported some of lua 5.2's stuff with beta 3, but we can try an older version of luaJIT if that would help?

**Comment by Zeblote** [comment]
For now, we got this to work by commenting out all of these compatibility functions in sol2:

```
lua_copy
lua_tointegerx
lua_tonumberx
lua_version
luaL_setfuncs
luaL_setmetatable
luaL_testudata
```

LuaJIT already defines them with beta 3, so they might need to be hidden behind a SOL_LUAJIT_VERSION check.

**Comment by ThePhD** [comment]
I still can't verify, but I'm just going to assume my tools are busted somehow and try again on another computer later to confirm.

In the meantime, I've gated those functions behind a version check and pushed to latest; let me know if it's still busted for you when you try the latest sol2.

**Comment by Zeblote** [comment]
Thanks, the new version works!
