### ISSUE TITLE
sol::light compile error

### ISSUE THREAD

**Issue by qinix** [ThePhD/sol2#1354]
I got following error when using `sol::light`

```
/.../sol2/include/sol/stack_push.hpp:655:29: error: invalid ‘static_cast’ from type ‘<unresolved overloaded function type>’ to type ‘void*’
  655 |    lua_pushlightuserdata(L, static_cast<void*>(l.value));
      | 
```

After diving the source code, I found inconsistency on `unqualified_pusher<light<T>>`. The `unqualified_pusher<light<T>>` is using `light<T>.value` as a pointer, but in `light<T>`'s definition, `light<T>.valule` is a function returning a pointer.

https://github.com/ThePhD/sol2/blob/64096348465b980e2f1d0e5ba9cbeea8782e8f27/include/sol/stack_push.hpp#L649-L658

https://github.com/ThePhD/sol2/blob/64096348465b980e2f1d0e5ba9cbeea8782e8f27/include/sol/types.hpp#L236-L238

**Comment by qinix** [comment]
Just found the bug was introduced in https://github.com/ThePhD/sol2/commit/d39330eab9495de7ad1faa980a4ac21d32b221ac#diff-f39e4f5b416258c6137530a4fc5324146bdc743b553712070ff58e3453931c60L200-R224
