### ISSUE TITLE
Failure to build on MacOS 10.15 due to a missing include of unordered_map.

### ISSUE THREAD

**Issue by beeperdeeper089** [ThePhD/sol2#1034]
When using Azure Pipelines to build Sol on MacOS 10.15 using ``AppleClang 11.0.3.11030032``, we're experiencing a build error along the lines of:
```
In file included from /Users/runner/work/1/s/Phoenix/ThirdParty/sol2/include/sol/usertype.hpp:29:
/Users/runner/work/1/s/Phoenix/ThirdParty/sol2/include/sol/usertype_storage.hpp:288:8: error: no template named 'unordered_map' in namespace 'std'
                std::unordered_map<string_view, index_call_storage> string_keys;
                ~~~~~^
/Users/runner/work/1/s/Phoenix/ThirdParty/sol2/include/sol/usertype_storage.hpp:289:8: error: no template named 'unordered_map' in namespace 'std'
                std::unordered_map<reference, reference, reference_hash, reference_equals> auxiliary_keys;
                ~~~~~^
```
It looks like it's relying on an implicit import from another file, and probably didn't work on Mac 🙄.

Full Build Log -> https://pastebin.com/bzUh0XE3

Thanks in advance if this gets fixed! :)

**Comment by ThePhD** [comment]
Fixed.

**Comment by tobyplowy** [comment]
@ThePhD Thanks.
