### ISSUE TITLE
Fail to build with Apple LLVM version 6.0 (clang-600.0.54) (based on LLVM 3.5svn) / 

### ISSUE THREAD

**Issue by paulsapps** [ThePhD/sol2#212]
https://travis-ci.org/paulsapps/alive/jobs/158986452

> /Users/travis/build/paulsapps/alive/3rdParty/sol2/single/sol/sol.hpp:122:32: error: no template named 'tuple_element_t' in namespace 'std'; did you mean 'tuple_element'?
>                 using tuple_element_t = std::tuple_element_t<N, unqualified_t<Tuple>>;
>                                         ~~~~~^~~~~~~~~~~~~~~
>                                              tuple_element
> /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__tuple:44:62: note: 'tuple_element' declared here
> template <size_t _Ip, class _Tp> class _LIBCPP_TYPE_VIS_ONLY tuple_element;
> 

Any ideas? Should be working because its clang 3.5? :(

**Comment by ThePhD** [comment]
Make sure you're using the right std version. Clang 3.5 does not default to using `std=c++1y` or `std=c++14`. You need to make sure that is specified in the XCode C++ version to use.

**Comment by paulsapps** [comment]
Adding in osx_image: xcode7 to travis.yml seems to have fixed it, I was passing -std=c++1y as seen here: https://github.com/paulsapps/alive/blob/dev/CMakeLists.txt#L518

**Comment by ThePhD** [comment]
Upgrading the `std::` lib is necessary, I suppose. If apple-clang bundles an old version of the standard lib in xcode6 I can't really do much about that. The library uses C++11/14 code and library constructs: if xcode6 has clang3.5 but is that piss poor about it's library, there's really nothing I can do except maybe add a note somewhere that XCode users beware.

**Comment by paulsapps** [comment]
Yeah fair enough, thanks!
